var hierarchy =
[
    [ "blit::API", "structblit_1_1API.html", null ],
    [ "blit::AudioChannel", "structblit_1_1AudioChannel.html", null ],
    [ "blit::BufferFile", "structblit_1_1BufferFile.html", null ],
    [ "blit::ButtonState", "structblit_1_1ButtonState.html", null ],
    [ "blit::File", "classblit_1_1File.html", null ],
    [ "blit::FileInfo", "structblit_1_1FileInfo.html", null ],
    [ "blit::Font", "structblit_1_1Font.html", null ],
    [ "blit::Profiler::GraphElement", "structblit_1_1Profiler_1_1GraphElement.html", null ],
    [ "blit::Menu::Item", "structblit_1_1Menu_1_1Item.html", null ],
    [ "blit::JPEGImage", "structblit_1_1JPEGImage.html", null ],
    [ "blit::Map", "structblit_1_1Map.html", null ],
    [ "blit::MapLayer", "structblit_1_1MapLayer.html", null ],
    [ "blit::Mat3", "structblit_1_1Mat3.html", null ],
    [ "blit::Mat4", "structblit_1_1Mat4.html", null ],
    [ "blit::Menu", "classblit_1_1Menu.html", null ],
    [ "blit::ProfilerProbe::Metrics", "structblit_1_1ProfilerProbe_1_1Metrics.html", null ],
    [ "mp3dec_frame_info_t", "structmp3dec__frame__info__t.html", null ],
    [ "mp3dec_t", "structmp3dec__t.html", null ],
    [ "blit::MP3Stream", "classblit_1_1MP3Stream.html", null ],
    [ "blit::packed_image", "structblit_1_1packed__image.html", null ],
    [ "blit::Particle", "structblit_1_1Particle.html", null ],
    [ "blit::ParticleGenerator", "structblit_1_1ParticleGenerator.html", null ],
    [ "blit::Pen", "structblit_1_1Pen.html", null ],
    [ "blit::Point", "structblit_1_1Point.html", null ],
    [ "blit::Profiler", "classblit_1_1Profiler.html", null ],
    [ "blit::ProfilerProbe", "classblit_1_1ProfilerProbe.html", null ],
    [ "blit::Rect", "structblit_1_1Rect.html", null ],
    [ "blit::RunningAverage< T >", "classblit_1_1RunningAverage.html", null ],
    [ "blit::RunningAverage< float >", "classblit_1_1RunningAverage.html", null ],
    [ "blit::ScopedProfilerProbe", "classblit_1_1ScopedProfilerProbe.html", null ],
    [ "blit::Size", "structblit_1_1Size.html", null ],
    [ "blit::Surface", "structblit_1_1Surface.html", [
      [ "blit::SpriteSheet", "structblit_1_1SpriteSheet.html", null ]
    ] ],
    [ "blit::TileMap", "structblit_1_1TileMap.html", null ],
    [ "blit::Timer", "structblit_1_1Timer.html", null ],
    [ "blit::timer_event_t", "structblit_1_1timer__event__t.html", null ],
    [ "blit::Tween", "structblit_1_1Tween.html", null ],
    [ "blit::Vec2", "structblit_1_1Vec2.html", null ],
    [ "blit::Vec3", "structblit_1_1Vec3.html", null ]
];